#!/bin/bash
set -euo pipefail

# install-agent-config.sh
# Reads config.json and secrets.json, hydrates templates, installs GSD framework,
# restores credentials, and prints a summary.
# Safe to run multiple times (naturally idempotent).

# Constants and paths
WORKSPACE_ROOT="/workspace"
CONFIG_FILE="$WORKSPACE_ROOT/config.json"
SECRETS_FILE="$WORKSPACE_ROOT/secrets.json"
AGENT_CONFIG_DIR="$WORKSPACE_ROOT/agent-config"
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-/home/node/.claude}"
SETTINGS_TEMPLATE="$AGENT_CONFIG_DIR/settings.json.template"
MCP_TEMPLATES_DIR="$AGENT_CONFIG_DIR/mcp-templates"

# JSON validation helper
validate_json() {
    local file="$1"
    local label="$2"
    if ! jq empty < "$file" &>/dev/null; then
        echo "[install] ERROR: $label is not valid JSON — skipping"
        return 1
    fi
    return 0
}

# Initialize counters for summary
CONFIG_STATUS="defaults — config.json not found"
SECRETS_STATUS="empty placeholders — secrets.json not found"
CREDS_STATUS="missing — manual login required"
MCP_COUNT=0
GSD_COMMANDS=0
GSD_AGENTS=0

# Load config.json (or use defaults)
if [ -f "$CONFIG_FILE" ]; then
    if validate_json "$CONFIG_FILE" "config.json"; then
        CONFIG_STATUS="loaded"
        LANGFUSE_HOST=$(jq -r '.langfuse.host // "http://host.docker.internal:3052"' "$CONFIG_FILE")
        EXTRA_DOMAINS=$(jq -r '.firewall.extra_domains // [] | join(" ")' "$CONFIG_FILE")
    else
        LANGFUSE_HOST="http://host.docker.internal:3052"
        EXTRA_DOMAINS=""
    fi
else
    echo "[install] config.json not found — using defaults"
    LANGFUSE_HOST="http://host.docker.internal:3052"
    EXTRA_DOMAINS=""
fi

# Load secrets.json (or use empty placeholders)
if [ -f "$SECRETS_FILE" ]; then
    if validate_json "$SECRETS_FILE" "secrets.json"; then
        SECRETS_STATUS="loaded"
        LANGFUSE_PUBLIC_KEY=$(jq -r '.langfuse.public_key // ""' "$SECRETS_FILE")
        LANGFUSE_SECRET_KEY=$(jq -r '.langfuse.secret_key // ""' "$SECRETS_FILE")

        # Check for missing individual secrets
        if [ -z "$LANGFUSE_PUBLIC_KEY" ]; then
            echo "[install] secrets.json: langfuse.public_key missing — tracing will not work"
        fi
        if [ -z "$LANGFUSE_SECRET_KEY" ]; then
            echo "[install] secrets.json: langfuse.secret_key missing — tracing will not work"
        fi
    else
        LANGFUSE_PUBLIC_KEY=""
        LANGFUSE_SECRET_KEY=""
    fi
else
    echo "[install] secrets.json not found — using empty placeholders"
    LANGFUSE_PUBLIC_KEY=""
    LANGFUSE_SECRET_KEY=""
fi

# Get MCP Gateway URL from environment or default
MCP_GATEWAY_URL="${MCP_GATEWAY_URL:-http://host.docker.internal:8811}"

# Generate firewall-domains.conf from config.json (GEN-01, GEN-02)
FIREWALL_CONF="$WORKSPACE_ROOT/.devcontainer/firewall-domains.conf"
CORE_DOMAINS=(
    # Package registries
    "registry.npmjs.org"
    "registry.npmjs.com"
    # Anthropic services
    "api.anthropic.com"
    "sentry.io"
    "statsig.anthropic.com"
    "statsig.com"
    # VS Code marketplace
    "marketplace.visualstudio.com"
    "gallerycdn.vsassets.io"
    "gallery.vsassets.io"
    "vsassets.io"
    "vscode.blob.core.windows.net"
    "update.code.visualstudio.com"
    # Debian repositories
    "deb.debian.org"
    "security.debian.org"
    # GitHub (IP ranges handled separately by init-firewall.sh)
    "github.com"
    "objects.githubusercontent.com"
    "uploads.github.com"
    "codeload.github.com"
    # Cloudflare
    "api.cloudflare.com"
    "dash.cloudflare.com"
    "workers.dev"
    # Python packages
    "pypi.python.org"
    "pypi.org"
    "files.pythonhosted.org"
    # Other
    "storage.googleapis.com"
    "json.schemastore.org"
    # API provider domains — always present for future agent use (GEN-02)
    "api.openai.com"
    "generativelanguage.googleapis.com"
)

{
    echo "# Generated by install-agent-config.sh — do not edit manually"
    echo "# Core domains (always present)"
    printf '%s\n' "${CORE_DOMAINS[@]}"
    echo ""
    echo "# Extra domains from config.json"
} > "$FIREWALL_CONF"

# Append extra_domains from config.json
if [ -f "$CONFIG_FILE" ]; then
    EXTRA_LIST=$(jq -r '.firewall.extra_domains // [] | .[]' "$CONFIG_FILE" 2>/dev/null || true)
    if [ -n "$EXTRA_LIST" ]; then
        echo "$EXTRA_LIST" >> "$FIREWALL_CONF"
    fi
fi

DOMAIN_COUNT=$(grep -c '^[^#]' "$FIREWALL_CONF" | tr -d '[:space:]')
echo "[install] Generated firewall-domains.conf with $DOMAIN_COUNT domain(s)"

# Generate .vscode/settings.json from config.json (GEN-03)
VSCODE_DIR="$WORKSPACE_ROOT/.vscode"
mkdir -p "$VSCODE_DIR"

# Read git scan paths from config.json
GIT_SCAN_PATHS='[".", "gitprojects/adventure-alerts"]'
if [ -f "$CONFIG_FILE" ]; then
    CONFIGURED_PATHS=$(jq -r '.vscode.git_scan_paths // []' "$CONFIG_FILE" 2>/dev/null || echo "[]")
    # If configured paths is non-empty array, use it; otherwise auto-detect
    PATH_COUNT=$(echo "$CONFIGURED_PATHS" | jq 'length' 2>/dev/null || echo "0")
    if [ "$PATH_COUNT" -gt 0 ]; then
        # User specified paths — prepend "." (workspace root) if not present
        GIT_SCAN_PATHS=$(echo "$CONFIGURED_PATHS" | jq '. as $paths | if (. | index(".")) then $paths else ["."] + $paths end')
    else
        # Auto-detect: find .git directories under gitprojects/
        DETECTED='["."]'
        if [ -d "$WORKSPACE_ROOT/gitprojects" ]; then
            for git_dir in "$WORKSPACE_ROOT/gitprojects"/*/.git; do
                if [ -d "$git_dir" ]; then
                    project_name=$(basename "$(dirname "$git_dir")")
                    DETECTED=$(echo "$DETECTED" | jq --arg p "gitprojects/$project_name" '. + [$p]')
                fi
            done
        fi
        GIT_SCAN_PATHS="$DETECTED"
    fi
fi

jq -n --argjson paths "$GIT_SCAN_PATHS" '{"git.scanRepositories": $paths}' > "$VSCODE_DIR/settings.json"
echo "[install] Generated .vscode/settings.json with $(echo "$GIT_SCAN_PATHS" | jq 'length') scan path(s)"

# Create directories (idempotent)
mkdir -p "$CLAUDE_DIR/skills"
mkdir -p "$CLAUDE_DIR/hooks"
mkdir -p "$CLAUDE_DIR/agents"
mkdir -p "$CLAUDE_DIR/commands"

# Copy skills from agent-config to runtime location (AGT-03)
SKILLS_COUNT=0
if [ -d "$AGENT_CONFIG_DIR/skills" ]; then
    cp -r "$AGENT_CONFIG_DIR/skills/"* "$CLAUDE_DIR/skills/" 2>/dev/null || true
    SKILLS_COUNT=$(find "$AGENT_CONFIG_DIR/skills" -maxdepth 1 -mindepth 1 -type d 2>/dev/null | wc -l)
    echo "[install] Copied $SKILLS_COUNT skill(s) to $CLAUDE_DIR/skills/"
fi

# Copy hooks from agent-config to runtime location (AGT-04)
HOOKS_COUNT=0
if [ -d "$AGENT_CONFIG_DIR/hooks" ]; then
    cp "$AGENT_CONFIG_DIR/hooks/"* "$CLAUDE_DIR/hooks/" 2>/dev/null || true
    HOOKS_COUNT=$(find "$AGENT_CONFIG_DIR/hooks" -maxdepth 1 -type f 2>/dev/null | wc -l)
    echo "[install] Copied $HOOKS_COUNT hook(s) to $CLAUDE_DIR/hooks/"
fi

# Copy commands from agent-config, non-destructive — don't overwrite GSD (AGT-05)
COMMANDS_COUNT=0
if [ -d "$AGENT_CONFIG_DIR/commands" ]; then
    cp -rn "$AGENT_CONFIG_DIR/commands/"* "$CLAUDE_DIR/commands/" 2>/dev/null || true
    COMMANDS_COUNT=$(find "$AGENT_CONFIG_DIR/commands" -maxdepth 1 -mindepth 1 2>/dev/null | wc -l)
    echo "[install] Copied $COMMANDS_COUNT command source(s) to $CLAUDE_DIR/commands/ (non-destructive)"
fi

# Generate settings.local.json from template
if [ -f "$SETTINGS_TEMPLATE" ]; then
    sed -e "s|{{LANGFUSE_HOST}}|$LANGFUSE_HOST|g" \
        -e "s|{{LANGFUSE_PUBLIC_KEY}}|$LANGFUSE_PUBLIC_KEY|g" \
        -e "s|{{LANGFUSE_SECRET_KEY}}|$LANGFUSE_SECRET_KEY|g" \
        "$SETTINGS_TEMPLATE" > "$CLAUDE_DIR/settings.local.json"
    echo "[install] Generated settings.local.json"
else
    echo "[install] WARNING: settings.json.template not found — skipping settings generation"
fi

# Restore Claude credentials (if available)
if [ -f "$SECRETS_FILE" ]; then
    CLAUDE_CREDS=$(jq -e '.claude.credentials // {}' "$SECRETS_FILE" 2>/dev/null || echo "{}")
    # Check if credentials object is non-empty
    if [ "$CLAUDE_CREDS" != "{}" ] && [ "$CLAUDE_CREDS" != "null" ]; then
        echo "$CLAUDE_CREDS" > "$CLAUDE_DIR/.credentials.json"
        chmod 600 "$CLAUDE_DIR/.credentials.json"
        CREDS_STATUS="restored"
        echo "[install] Claude credentials restored"
    else
        echo "[install] Claude credentials not found — manual login required after first start"
    fi
else
    echo "[install] Claude credentials not found — manual login required after first start"
fi

# Generate .mcp.json from enabled MCP templates
if [ -f "$CONFIG_FILE" ]; then
    # Get list of enabled MCP servers
    ENABLED_SERVERS=$(jq -r '.mcp_servers | to_entries[] | select(.value.enabled == true) | .key' "$CONFIG_FILE" 2>/dev/null || echo "")

    if [ -n "$ENABLED_SERVERS" ]; then
        # Build combined MCP config
        MCP_JSON='{"mcpServers":{}}'

        for SERVER in $ENABLED_SERVERS; do
            TEMPLATE_FILE="$MCP_TEMPLATES_DIR/${SERVER}.json"
            if [ -f "$TEMPLATE_FILE" ]; then
                # Hydrate template and merge into combined config
                HYDRATED=$(sed "s|{{MCP_GATEWAY_URL}}|$MCP_GATEWAY_URL|g" "$TEMPLATE_FILE")
                MCP_JSON=$(echo "$MCP_JSON" | jq --argjson server "{\"$SERVER\": $HYDRATED}" '.mcpServers += $server')
                MCP_COUNT=$((MCP_COUNT + 1))
            else
                echo "[install] WARNING: Template $TEMPLATE_FILE not found for enabled server $SERVER"
            fi
        done

        echo "$MCP_JSON" > "$WORKSPACE_ROOT/.mcp.json"
        echo "[install] Generated .mcp.json with $MCP_COUNT server(s)"
    else
        # No enabled servers, create default with mcp-gateway
        echo '{"mcpServers":{"mcp-gateway":{"type":"sse","url":"'"$MCP_GATEWAY_URL"'/sse"}}}' > "$WORKSPACE_ROOT/.mcp.json"
        MCP_COUNT=1
        echo "[install] Generated .mcp.json with 1 server(s) (default)"
    fi
else
    # No config.json, create default with mcp-gateway
    echo '{"mcpServers":{"mcp-gateway":{"type":"sse","url":"'"$MCP_GATEWAY_URL"'/sse"}}}' > "$WORKSPACE_ROOT/.mcp.json"
    MCP_COUNT=1
    echo "[install] Generated .mcp.json with 1 server(s) (default)"
fi

# Detect unresolved {{PLACEHOLDER}} tokens in generated files (GEN-06)
UNRESOLVED=""
for generated_file in "$CLAUDE_DIR/settings.local.json" "$WORKSPACE_ROOT/.mcp.json"; do
    if [ -f "$generated_file" ]; then
        tokens=$(grep -oP '\{\{[A-Z_]+\}\}' "$generated_file" 2>/dev/null || true)
        if [ -n "$tokens" ]; then
            UNRESOLVED="$UNRESOLVED $tokens"
            # Replace unresolved tokens with empty strings
            sed -i 's/{{[A-Z_]*}}//g' "$generated_file"
        fi
    fi
done
if [ -n "$UNRESOLVED" ]; then
    echo "[install] WARNING: Unresolved placeholders replaced with empty strings:$UNRESOLVED"
fi

# Install GSD framework
if [ -d "$CLAUDE_DIR/commands/gsd" ] && [ "$(ls -A "$CLAUDE_DIR/commands/gsd" 2>/dev/null)" ]; then
    echo "[install] GSD: already installed, skipping"
    # Count existing installation
    GSD_COMMANDS=$(find "$CLAUDE_DIR/commands/gsd" -name "*.md" 2>/dev/null | wc -l || echo 0)
    GSD_AGENTS=$(find "$CLAUDE_DIR/agents" -name "*.md" 2>/dev/null | wc -l || echo 0)
else
    echo "[install] Installing GSD framework..."
    if npx get-shit-done-cc --claude --global > /dev/null 2>&1; then
        echo "[install] GSD framework installed"
        # Count after installation
        GSD_COMMANDS=$(find "$CLAUDE_DIR/commands/gsd" -name "*.md" 2>/dev/null | wc -l || echo 0)
        GSD_AGENTS=$(find "$CLAUDE_DIR/agents" -name "*.md" 2>/dev/null | wc -l || echo 0)
    else
        echo "[install] WARNING: GSD installation failed"
        GSD_COMMANDS=0
        GSD_AGENTS=0
    fi
fi

# Print summary
echo "[install] --- Summary ---"
echo "[install] Config: $CONFIG_STATUS"
echo "[install] Secrets: $SECRETS_STATUS"
echo "[install] Settings: generated"
echo "[install] Credentials: $CREDS_STATUS"
echo "[install] Skills: $SKILLS_COUNT skill(s)"
echo "[install] Hooks: $HOOKS_COUNT hook(s)"
echo "[install] Commands: $COMMANDS_COUNT command source(s)"
echo "[install] MCP: $MCP_COUNT server(s)"
echo "[install] GSD: $GSD_COMMANDS commands + $GSD_AGENTS agents"
echo "[install] Done."
